require 'buildr'
require 'buildr/intellij_idea/version'
require 'buildr/intellij_idea/idea_file'
require 'buildr/intellij_idea/idea_module'
require 'buildr/intellij_idea/idea_project'
require 'buildr/intellij_idea/project_extension'
